### ISSUE TITLE
Weird 3D look in latest builds

### ISSUE THREAD

**Issue by mikrosk** [freemint/teradesk#3]
Haven't tested older builds but this is how the delete dialog looks in 4.08:

![td408](https://user-images.githubusercontent.com/3062260/148125740-1ecb95d9-fefb-4e45-aed0-24e618623e5e.png)

and this is how it looks in latest build:

![td_latest](https://user-images.githubusercontent.com/3062260/148125785-20830fe1-bd18-400e-88cd-c6298c4fd720.png)

Other dialogs (e.g. shutdown) look ever worse.

**Comment by th-otto** [comment]
Do you mean the new 3D look in EmuTOS? But this hasn't anything to do with teradesk builds?

**Comment by mikrosk** [comment]
I don't know who's to blame but the point is that the old Teradesk 4.08 doesn't do it, regardless of EmuTOS version (both screenshots were made as started from EmuTOS).

**Comment by th-otto** [comment]
Just had a look at it again, and still don't understand why the two versions behave differently. The background of the dialog title is drawn by ub_title : https://github.com/freemint/teradesk/blob/d558e585352d39bc0a3e803b45876653b97db8be/library/xdialog/xddraw.c#L1467-L1474

So the color depends on xd_colaes flag and the value returned by xd_get_3d_colour(), which should be xd_ind_col in this case.

Those flags are set here https://github.com/freemint/teradesk/blob/d558e585352d39bc0a3e803b45876653b97db8be/library/xdialog/xdialog.c#L2607-L2608 and https://github.com/freemint/teradesk/blob/d558e585352d39bc0a3e803b45876653b97db8be/library/xdialog/xdialog.c#L63

Which is the same logic both for 4.08 and the current version.

Unfortunately, i can't compile the original 4.08 version with Pure-C (i did lots of changes afterwards to get it compiled), and as we saw recently, i can't use a gcc-compiled  version with SingleTOS either. Any ideas were to look?

**Comment by mikrosk** [comment]
> i can't compile the original 4.08 version with Pure-C

How so? The original sources were Pure C, weren't they? Or was it AHCC later on? Anyway, it should be still possible to compile the original so you can put some debug output in there.

Maybe the flag is randomly overwritten by something?

**Comment by th-otto** [comment]
I think AHCC was used, but by using some extensions (eg. for the Mint functions) which are not available in the original Pure-C libraries and headers. Try to compile it with Pure-C, and you will get lots of missing/mismatched declarations.

**Comment by th-otto** [comment]
Ok, after some twiddling i got it compiled with Pure-C (although i'm quite sure that will be some problems with functions being wrongly declared). But at least it starts up. However, dialog look like this:
![Screenshot_20230201_165002](https://user-images.githubusercontent.com/12425871/216093857-56e97726-b215-4e7d-8329-12606aad19ed.png)
Apart from the wrong font size, they use the same grey background as current version. This was using TOS 3.06 (no aes 3d, no color icons).

**Comment by mikrosk** [comment]
Oh. But you do see the original PRG without the 3D effects on the same setup, right?

**Comment by th-otto** [comment]
Don't know which "original program" you tested with. I only have an older version here (4.06), and that looks the same on  that setup.

**Comment by th-otto** [comment]
BTW, the shutdown dialog looks like this in current version:

![Screenshot_20230202_102752](https://user-images.githubusercontent.com/12425871/216285186-a878cc05-3b9c-4809-98f6-5958091d037f.png)

Is that really that bad?

**Comment by mikrosk** [comment]
I mean the last official binary released by Djordje: http://solair.eunet.rs/~vdjole/tera408b.zip.

TOS 3.06 + DESKTOPS.PRG of Teradesk 4.08:

![grab0002](https://user-images.githubusercontent.com/3062260/216287584-63e347c2-9da6-4d16-88bb-107263e27c73.png)

TOS 3.06 + DESKTOPS.PRG of one of your snapshots:

![grab0001](https://user-images.githubusercontent.com/3062260/216287640-53df764e-d50e-4dfd-bccc-92bc5c9199ed.png)

So yes, it is really that bad.

**Comment by th-otto** [comment]
![Screenshot_20230202_104944](https://user-images.githubusercontent.com/12425871/216291107-b33ccc71-cc7f-4bc3-af0c-3ae9645038c0.png)

... also has grey buttons here. And the source archive (which is also still available there) should be the one which was checked in as our tag VER_4_08 which i used in the tests above.

Your radio buttons are admittedly ugly, but i think this only happens in low resolution.

**Comment by mikrosk** [comment]
I could live with a grey button here and there but what is causing the difference in backgrounds and radio buttons then? Do you think that source code released along with it (http://solair.eunet.rs/~vdjole/tera408s.zip) is not matching the binary? That would be rather surprising as your 4.06 exhibits this behaviour, too (and I have never noticed it _at all_ -- and I've been using Teradesk for many, many years).

**Comment by th-otto** [comment]
Yes, i use teradesk too, but only in MiNT environments.

I have no idea why you don't get grey buttons (and some other 3d look). The code is quite clear, the flag is always set with >= 16 colors, and that seem to be the case for quite some time.

Since the binary that i have compiled from the source, and the one from his site behave the same, i don't think it is a mismatch between source & binary.

Only thing that you could maybe try, is to compile the source of 4.08 yourself, and see if that makes a difference. When you do this, make sure that you *don't* have an include path set in your shell options (the project file uses the one from  the include directory, which are not identical to the original ones)

**Comment by mikrosk** [comment]
> Since the binary that i have compiled from the source, and the one from his site behave the same, i don't think it is a mismatch between source & binary.

So you mean that if you download teradesk 4.08 from his site, run DESKTOPS.PRG, you _do_ see the grey backround in the desktop preferences dialog, too?

I think it's crucial to establish whether it is a difference in our setup or you have just looked at a different dialog and/or in a different resolution.

I boot TOS 3.06, stay in ST-LOW, open Desk preferences and the grey background is there in your builds and not in the official.

**Comment by th-otto** [comment]
Yes i do have grey buttons with his build (the last snapshot was from this program), but only for the buttons, not the dialog itself.

So yes, there must be something different with the setup. So imho the only way to find the cause is that you compile it yourself, then start adding debug printf or whatever to find out what is different.

**Comment by mikrosk** [comment]
Having TOS 3.06 and booting into ST-LOW doesn't seem like a lot of room for setup differences - I think we both agree that Hatari can't influence this kind of behaviour. :-P

**Comment by th-otto** [comment]
Sorry, but i'm currently busy trying to fix the quirks in cflib, so that QED works again. Can't you just try to figure it out yourself?

BTW, when you say DESKTOP*S*.PRG, do you mean the singletos version (its normally named desktos.prg). That behaves slightly different, indeed.

**Comment by mikrosk** [comment]
> BTW, when you say DESKTOPS.PRG, do you mean the singletos version

Indeed I do. I'll try to find some time later to take a look if you will be still busy.

**Comment by th-otto** [comment]
Ok, there is a difference in behaviour because of a variable that i removed at some time. In the original version, it was queried here: https://github.com/freemint/teradesk/blob/d558e585352d39bc0a3e803b45876653b97db8be/library/xdialog/xddraw.c#L351
and it was set here:
https://github.com/freemint/teradesk/blob/d558e585352d39bc0a3e803b45876653b97db8be/library/xdialog/xdialog.c#L2567
https://github.com/freemint/teradesk/blob/d558e585352d39bc0a3e803b45876653b97db8be/library/xdialog/xdialog.c#L2639-L2650 or here https://github.com/freemint/teradesk/blob/d558e585352d39bc0a3e803b45876653b97db8be/library/xdialog/xdialog.c#L2731-L2733

Especially the 3rd occurrence was imho nonsense, since the presence of appl_getinfo() does not indicate AES 4.x (WINX  also supports appl_getinfo()). But surely that had an influence on the query in xd_is3dobj(). However, reverting it to the previous behaviour i now get
![Screenshot_20230202_185552](https://user-images.githubusercontent.com/12425871/216403967-318fed31-f45a-4431-9ae5-8ec04bc44d3d.png)

when running EmuTOS, but not when running TOS 3.06. That's not much better...

**Comment by mikrosk** [comment]
I guess that is thanks to the fairly recent addition of 3D look support to EmuTOS.

Don't get me wrong, I have nothing against 3D buttons and such but a) I wanted to make sure that it is understood when (and why) the change of 3D has occured and b) that it looks at least equally good.

So far, I'd be totally fine to get the flat look in TOS 3.06 and semi-3D look in EmuTOS (as it is native now).

IMO it would look pretty strange if only Teradesk had some sort of 3D buttons in TOS 3.06 while all other applications would look flat.

**Comment by th-otto** [comment]
> I guess that is thanks to the fairly recent addition of 3D look support to EmuTOS.

Yes, for sure. You can see that because the "Open" button is slightly larger.

> IMO it would look pretty strange if only Teradesk had some sort of 3D buttons in TOS 3.06 while all other applications would look flat.

Its not unusual that applications draw some elements like buttons with their own functions, and use 3D look for that. But typically they do that only when the AES does it, too. ORCS can also do that, but then either both the background and the buttons are grey, or white, not that strange mix in teradesk. 

The patch where i removed that flag tried to simplify things (look at all the flags that are used for this in xddraw.c, that's quite ugly and hard to understand). 

Anyway, i think i'll mostly revert that patch, so things will look like before. Teradesk will mostly be used in Multitasking-environments anyway, and there xd_aes4_0 will always be set (because appl_getinfo is present).

**Comment by mikrosk** [comment]
Confirmed as fixed, closing.
