### ISSUE TITLE
Teradesk should better detect the extended RSC format

### ISSUE THREAD

**Issue by mikrosk** [freemint/teradesk#8]
As described [here](https://sourceforge.net/p/emutos/mailman/emutos-devel/thread/c024cf71-2c8e-26ff-c763-4db1aadab793%40gmx.net/#msg37770597) and [here](https://sourceforge.net/p/emutos/mailman/emutos-devel/thread/3579685.WbyNdk4fJJ%40earendil/#msg37770841).

**Comment by th-otto** [comment]
Can someone please test the attached programs? They contain a patch that load the monochrome icons.rsc using a custom function.

Note that the color icon resource file is still loaded using the AES function. This is done because the new routine handles coloricons correctly, but does not transform the icon data, or installs own functions to draw them. That also means that you still don't get color icons if the AES does not support it. And it also implies that the cicons.rsc file is using the old format which supports only 64k (the actual file is much larger of course, but only due to the color icon data; the basic resource file from Phillipe is less than 9k and thus does not need an extended header).

The attached file contains programs for 68k and coldfire. The 68k version was compiled by Pure-C. I currently get strange crashes when using the gcc-compiled version for 68k, upon quit from teradesk EmuTOS either crashes or hangs. But that happens also when using a program without the patch, so must be related to something else.

[teradesk.zip](https://github.com/freemint/teradesk/files/10537743/teradesk.zip)

**Comment by th-otto** [comment]
Fixed by https://github.com/freemint/teradesk/commit/83c212fbde4968527f4be3d41aecf278c46600b8
